let fake_data = [
    { "name": "Canis lupus lycaon", "brand": "Gabvine", "size": 42, "price": 74, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    { "name": "Uraeginthus granatina", "brand": "Skipstorm", "size": 35, "price": 65, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Green" },
    { "name": "Pterocles gutturalis", "brand": "Brainbox", "size": 38, "price": 87, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    { "name": "Pitangus sulphuratus", "brand": "Vipe", "size": 36, "price": 82, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    { "name": "Mirounga leonina", "brand": "Oodoo", "size": 39, "price": 67, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Maroon" },
    { "name": "Lasiorhinus latifrons", "brand": "Lajo", "size": 40, "price": 14, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Maroon" },
    { "name": "Plegadis ridgwayi", "brand": "Wordware", "size": 42, "price": 21, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Mauv" },
    { "name": "Dendrocitta vagabunda", "brand": "Tagcat", "size": 38, "price": 67, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    { "name": "Canis latrans", "brand": "Brainbox", "size": 35, "price": 64, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Khaki" },
    { "name": "Rangifer tarandus", "brand": "Skyvu", "size": 42, "price": 89, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Goldenrod" },
    { "name": "Bubo virginianus", "brand": "Meezzy", "size": 35, "price": 100, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Crimson" },
    { "name": "Ammospermophilus nelsoni", "brand": "Jaxbean", "size": 35, "price": 26, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    { "name": "Egretta thula", "brand": "Wordware", "size": 38, "price": 76, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    { "name": "Pseudalopex gymnocercus", "brand": "Browsedrive", "size": 42, "price": 79, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    { "name": "Coluber constrictor foxii", "brand": "Zoozzy", "size": 41, "price": 45, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    { "name": "unavailable", "brand": "Zooxo", "size": 40, "price": 39, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    { "name": "Dipodomys deserti", "brand": "Meevee", "size": 37, "price": 92, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    { "name": "Acridotheres tristis", "brand": "Skyba", "size": 37, "price": 16, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    { "name": "Alcelaphus buselaphus cokii", "brand": "Topdrive", "size": 36, "price": 31, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Mauv" },
    { "name": "Dendrocitta vagabunda", "brand": "Roomm", "size": 39, "price": 45, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Goldenrod" },
    { "name": "Semnopithecus entellus", "brand": "Wikibox", "size": 41, "price": 42, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Blue" },
    { "name": "Ceryle rudis", "brand": "Zoonoodle", "size": 38, "price": 14, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Mauv" },
    { "name": "Castor canadensis", "brand": "Cogilith", "size": 42, "price": 38, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    { "name": "Callipepla gambelii", "brand": "InnoZ", "size": 42, "price": 53, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    { "name": "Mirounga leonina", "brand": "Feedmix", "size": 37, "price": 37, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Purple" },
    { "name": "Loris tardigratus", "brand": "Wordtune", "size": 35, "price": 49, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    { "name": "Cynictis penicillata", "brand": "Teklist", "size": 35, "price": 44, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    { "name": "Camelus dromedarius", "brand": "Devify", "size": 41, "price": 85, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Green" },
    { "name": "Diceros bicornis", "brand": "Zoozzy", "size": 41, "price": 76, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    { "name": "Sula dactylatra", "brand": "Browsecat", "size": 37, "price": 77, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Aquamarine" },
    { "name": "Taxidea taxus", "brand": "Dabfeed", "size": 41, "price": 23, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Puce" },
    { "name": "Scolopax minor", "brand": "Thoughtbridge", "size": 39, "price": 67, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Fuscia" },
    { "name": "Trichechus inunguis", "brand": "Podcat", "size": 36, "price": 74, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Violet" },
    { "name": "Cebus albifrons", "brand": "Wikido", "size": 35, "price": 89, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Red" },
    { "name": "Felis silvestris lybica", "brand": "Meezzy", "size": 36, "price": 58, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Mauv" },
    { "name": "Felis libyca", "brand": "Realfire", "size": 41, "price": 55, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    { "name": "Naja haje", "brand": "Reallinks", "size": 37, "price": 87, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Maroon" },
    { "name": "Ephipplorhynchus senegalensis", "brand": "Gabvine", "size": 41, "price": 45, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    { "name": "Tursiops truncatus", "brand": "Aibox", "size": 35, "price": 12, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Goldenrod" },
    { "name": "Butorides striatus", "brand": "Thoughtbridge", "size": 35, "price": 10, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    { "name": "Procyon lotor", "brand": "Twitterwire", "size": 41, "price": 79, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    { "name": "Egretta thula", "brand": "Yabox", "size": 35, "price": 92, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    { "name": "Ardea cinerea", "brand": "Yotz", "size": 38, "price": 78, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    { "name": "Limnocorax flavirostra", "brand": "Youspan", "size": 38, "price": 79, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    { "name": "Corvus albus", "brand": "Devify", "size": 41, "price": 65, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Turquoise" },
    { "name": "Tayassu tajacu", "brand": "Twitterbridge", "size": 41, "price": 73, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    { "name": "Oreamnos americanus", "brand": "Gabtype", "size": 37, "price": 21, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    { "name": "Phoca vitulina", "brand": "Twitternation", "size": 42, "price": 53, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Puce" },
    { "name": "Anas bahamensis", "brand": "Fivespan", "size": 36, "price": 44, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    { "name": "Phoenicopterus ruber", "brand": "Gigaclub", "size": 35, "price": 28, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    { "name": "Bucephala clangula", "brand": "Avamm", "size": 35, "price": 50, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Aquamarine" },
    { "name": "Phalacrocorax brasilianus", "brand": "Jabbertype", "size": 40, "price": 90, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    { "name": "Tockus flavirostris", "brand": "Devbug", "size": 40, "price": 40, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Crimson" },
    { "name": "Oncorhynchus nerka", "brand": "Bubblemix", "size": 40, "price": 98, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    { "name": "Colobus guerza", "brand": "Tagchat", "size": 35, "price": 76, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Orange" },
    { "name": "Nyctea scandiaca", "brand": "Eimbee", "size": 38, "price": 50, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    { "name": "Graspus graspus", "brand": "Einti", "size": 42, "price": 17, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    { "name": "Tragelaphus strepsiceros", "brand": "Eabox", "size": 42, "price": 10, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Turquoise" },
    { "name": "Dusicyon thous", "brand": "Photofeed", "size": 39, "price": 85, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Mauv" },
    { "name": "Oreamnos americanus", "brand": "Shufflebeat", "size": 39, "price": 40, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    { "name": "Spizaetus coronatus", "brand": "Roombo", "size": 39, "price": 15, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Puce" },
    { "name": "Meleagris gallopavo", "brand": "Yamia", "size": 36, "price": 28, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    { "name": "Anthropoides paradisea", "brand": "Jaxnation", "size": 39, "price": 25, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Mauv" },
    { "name": "Larus novaehollandiae", "brand": "Dazzlesphere", "size": 39, "price": 45, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    { "name": "Ardea golieth", "brand": "Kazio", "size": 36, "price": 86, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Indigo" },
    { "name": "Papilio canadensis", "brand": "Myworks", "size": 35, "price": 39, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Aquamarine" },
    { "name": "Junonia genoveua", "brand": "Divavu", "size": 39, "price": 59, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Red" },
    { "name": "Tapirus terrestris", "brand": "Linktype", "size": 39, "price": 86, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Blue" },
    { "name": "Loxodonta africana", "brand": "Quire", "size": 40, "price": 46, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    { "name": "Felis serval", "brand": "Oyonder", "size": 38, "price": 33, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Indigo" },
    { "name": "Cacatua galerita", "brand": "Edgeclub", "size": 40, "price": 22, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Purple" },
    { "name": "Macaca radiata", "brand": "Youspan", "size": 38, "price": 70, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    { "name": "Pelecanus conspicillatus", "brand": "Zoombox", "size": 39, "price": 54, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Red" },
    { "name": "Odocoileus hemionus", "brand": "Youopia", "size": 39, "price": 61, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    { "name": "Anhinga rufa", "brand": "Browseblab", "size": 41, "price": 74, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Maroon" },
    { "name": "Ictonyx striatus", "brand": "Zoonder", "size": 35, "price": 77, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Yellow" },
    { "name": "Anthropoides paradisea", "brand": "Divape", "size": 36, "price": 54, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    { "name": "Agkistrodon piscivorus", "brand": "Leexo", "size": 40, "price": 78, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Mauv" },
    { "name": "Pteronura brasiliensis", "brand": "Riffpath", "size": 37, "price": 14, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    { "name": "Ourebia ourebi", "brand": "Brightdog", "size": 40, "price": 38, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Green" },
    { "name": "Marmota monax", "brand": "Shuffletag", "size": 36, "price": 43, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Maroon" },
    { "name": "Varanus sp.", "brand": "Fiveclub", "size": 42, "price": 24, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    { "name": "Passer domesticus", "brand": "Blogspan", "size": 42, "price": 33, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    { "name": "Nycticorax nycticorax", "brand": "Yodo", "size": 41, "price": 80, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    { "name": "Pteropus rufus", "brand": "Fadeo", "size": 36, "price": 41, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Red" },
    { "name": "Laniaurius atrococcineus", "brand": "Lajo", "size": 40, "price": 57, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Pink" },
    { "name": "Ploceus rubiginosus", "brand": "Jabbersphere", "size": 40, "price": 77, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    { "name": "Helogale undulata", "brand": "Edgeclub", "size": 41, "price": 94, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    { "name": "Choloepus hoffmani", "brand": "Dynabox", "size": 36, "price": 14, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Purple" },
    { "name": "Kobus leche robertsi", "brand": "Linklinks", "size": 42, "price": 93, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Goldenrod" },
    { "name": "Ara chloroptera", "brand": "Quire", "size": 38, "price": 21, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Orange" },
    { "name": "Larus dominicanus", "brand": "Innojam", "size": 42, "price": 24, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    { "name": "Heloderma horridum", "brand": "Quatz", "size": 37, "price": 23, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Puce" },
    { "name": "Corallus hortulanus cooki", "brand": "Edgeblab", "size": 36, "price": 42, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Green" },
    { "name": "Dendrohyrax brucel", "brand": "Layo", "size": 35, "price": 84, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    { "name": "Acrobates pygmaeus", "brand": "Yakijo", "size": 37, "price": 25, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Goldenrod" },
    { "name": "Cebus nigrivittatus", "brand": "Vidoo", "size": 41, "price": 83, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Blue" },
    { "name": "Dicrurus adsimilis", "brand": "Katz", "size": 36, "price": 99, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    { "name": "Merops bullockoides", "brand": "Trilith", "size": 42, "price": 38, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    { "name": "Balearica pavonina", "brand": "Devbug", "size": 42, "price": 53, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Aquamarine" },
    { "name": "Paroaria gularis", "brand": "Thoughtsphere", "size": 40, "price": 53, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Goldenrod" },
    { "name": "Naja haje", "brand": "Cogidoo", "size": 35, "price": 81, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Red" },
    { "name": "Pseudalopex gymnocercus", "brand": "Leenti", "size": 39, "price": 64, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Red" },
    { "name": "Phascogale calura", "brand": "Realfire", "size": 35, "price": 55, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    { "name": "Alligator mississippiensis", "brand": "Twitterwire", "size": 36, "price": 93, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    { "name": "Anhinga rufa", "brand": "Buzzbean", "size": 36, "price": 61, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    { "name": "Meles meles", "brand": "Livefish", "size": 41, "price": 84, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Purple" },
    { "name": "Pteropus rufus", "brand": "Skivee", "size": 38, "price": 28, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Fuscia" },
    // { "name": "Tiliqua scincoides", "brand": "Trudoo", "size": 41, "price": 45, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Crimson" },
    // { "name": "Lycaon pictus", "brand": "Shuffledrive", "size": 42, "price": 99, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Violet" },
    // { "name": "Phylurus milli", "brand": "Livefish", "size": 40, "price": 93, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    // { "name": "Laniaurius atrococcineus", "brand": "Omba", "size": 36, "price": 81, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    // { "name": "Nasua narica", "brand": "Tagfeed", "size": 37, "price": 57, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    // { "name": "Phoeniconaias minor", "brand": "Eimbee", "size": 37, "price": 37, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Khaki" },
    // { "name": "Zosterops pallidus", "brand": "Jayo", "size": 40, "price": 95, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Violet" },
    // { "name": "Paroaria gularis", "brand": "Mydo", "size": 39, "price": 23, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Puce" },
    // { "name": "Laniarius ferrugineus", "brand": "Wordware", "size": 37, "price": 23, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Red" },
    // { "name": "Libellula quadrimaculata", "brand": "Thoughtblab", "size": 39, "price": 79, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Puce" },
    // { "name": "Vanellus sp.", "brand": "Quatz", "size": 38, "price": 77, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    // { "name": "Coracias caudata", "brand": "Chatterpoint", "size": 41, "price": 52, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    // { "name": "Acrantophis madagascariensis", "brand": "Thoughtworks", "size": 40, "price": 60, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    // { "name": "Procyon lotor", "brand": "Fivespan", "size": 35, "price": 21, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    // { "name": "Cynictis penicillata", "brand": "Topicblab", "size": 35, "price": 31, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Fuscia" },
    // { "name": "Gorilla gorilla", "brand": "Janyx", "size": 40, "price": 92, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Macaca nemestrina", "brand": "Bubblebox", "size": 35, "price": 87, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    // { "name": "Phalacrocorax niger", "brand": "Trunyx", "size": 36, "price": 41, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    // { "name": "Smithopsis crassicaudata", "brand": "Livepath", "size": 40, "price": 10, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Indigo" },
    // { "name": "Podargus strigoides", "brand": "Riffpath", "size": 39, "price": 40, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    // { "name": "Uraeginthus angolensis", "brand": "Teklist", "size": 38, "price": 77, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Khaki" },
    // { "name": "Galictis vittata", "brand": "Lazz", "size": 40, "price": 68, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Orange" },
    // { "name": "Francolinus leucoscepus", "brand": "Lazzy", "size": 42, "price": 22, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    // { "name": "Macropus parryi", "brand": "Trudoo", "size": 36, "price": 81, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    // { "name": "Oncorhynchus nerka", "brand": "Eadel", "size": 42, "price": 28, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Indigo" },
    // { "name": "Lepilemur rufescens", "brand": "Browsedrive", "size": 35, "price": 50, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Otaria flavescens", "brand": "Myworks", "size": 37, "price": 62, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Ephipplorhynchus senegalensis", "brand": "Blogpad", "size": 38, "price": 78, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Crimson" },
    // { "name": "Nesomimus trifasciatus", "brand": "Realcube", "size": 42, "price": 80, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Aquamarine" },
    // { "name": "Turtur chalcospilos", "brand": "Gabvine", "size": 40, "price": 44, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Corvus brachyrhynchos", "brand": "Yacero", "size": 38, "price": 93, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Violet" },
    // { "name": "Tragelaphus angasi", "brand": "Zoombeat", "size": 39, "price": 12, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Stercorarius longicausus", "brand": "Fliptune", "size": 37, "price": 85, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Mauv" },
    // { "name": "Cervus unicolor", "brand": "Yodo", "size": 36, "price": 100, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    // { "name": "Aonyx cinerea", "brand": "Buzzshare", "size": 40, "price": 36, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Turquoise" },
    // { "name": "Rhea americana", "brand": "Zoomdog", "size": 39, "price": 75, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    // { "name": "Ardea cinerea", "brand": "Devify", "size": 38, "price": 100, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Turquoise" },
    // { "name": "Francolinus swainsonii", "brand": "Vitz", "size": 39, "price": 83, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Aonyx cinerea", "brand": "Rhynyx", "size": 41, "price": 36, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    // { "name": "Felis chaus", "brand": "Yozio", "size": 40, "price": 39, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Mauv" },
    // { "name": "Threskionis aethiopicus", "brand": "Oozz", "size": 39, "price": 81, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Yellow" },
    // { "name": "Ninox superciliaris", "brand": "Einti", "size": 40, "price": 46, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    // { "name": "Tragelaphus scriptus", "brand": "Zoomcast", "size": 39, "price": 29, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    // { "name": "Mirounga leonina", "brand": "Tagcat", "size": 35, "price": 24, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Puce" },
    // { "name": "Pycnonotus nigricans", "brand": "Realbridge", "size": 38, "price": 61, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Phasianus colchicus", "brand": "Gabtune", "size": 39, "price": 13, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    // { "name": "Papio ursinus", "brand": "Jamia", "size": 39, "price": 35, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Turquoise" },
    // { "name": "Bubulcus ibis", "brand": "Blognation", "size": 41, "price": 29, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Khaki" },
    // { "name": "Lophoaetus occipitalis", "brand": "Jayo", "size": 36, "price": 21, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    // { "name": "Eolophus roseicapillus", "brand": "Realpoint", "size": 40, "price": 82, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    // { "name": "Diomedea irrorata", "brand": "Aivee", "size": 36, "price": 18, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    // { "name": "Macropus agilis", "brand": "Voomm", "size": 37, "price": 49, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    // { "name": "Ramphastos tucanus", "brand": "Twimm", "size": 41, "price": 66, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Red" },
    // { "name": "Laniarius ferrugineus", "brand": "Jazzy", "size": 37, "price": 23, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Aquamarine" },
    // { "name": "Ovibos moschatus", "brand": "Browseblab", "size": 36, "price": 93, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Yellow" },
    // { "name": "Butorides striatus", "brand": "Camimbo", "size": 37, "price": 66, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Goldenrod" },
    // { "name": "Corvus albus", "brand": "Skinte", "size": 39, "price": 16, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    // { "name": "Microcebus murinus", "brand": "Trupe", "size": 38, "price": 12, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Crimson" },
    // { "name": "Choloepus hoffmani", "brand": "Miboo", "size": 36, "price": 56, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Dendrocitta vagabunda", "brand": "Lajo", "size": 35, "price": 10, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Violet" },
    // { "name": "Fregata magnificans", "brand": "Kazu", "size": 41, "price": 96, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Fuscia" },
    // { "name": "Columba palumbus", "brand": "Feedspan", "size": 37, "price": 84, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Pink" },
    // { "name": "Cervus duvauceli", "brand": "Thoughtsphere", "size": 41, "price": 61, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    // { "name": "Morelia spilotes variegata", "brand": "Zooveo", "size": 40, "price": 45, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Indigo" },
    // { "name": "Sarcophilus harrisii", "brand": "Voomm", "size": 39, "price": 66, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Maroon" },
    // { "name": "Limnocorax flavirostra", "brand": "Kayveo", "size": 39, "price": 67, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Puce" },
    // { "name": "Platalea leucordia", "brand": "Gigazoom", "size": 41, "price": 55, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" },
    // { "name": "Cynomys ludovicianus", "brand": "Yata", "size": 39, "price": 89, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Red" },
    // { "name": "Anser caerulescens", "brand": "Tanoodle", "size": 37, "price": 40, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    // { "name": "Felis silvestris lybica", "brand": "Vitz", "size": 42, "price": 38, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    // { "name": "Pseudoleistes virescens", "brand": "Jabberstorm", "size": 42, "price": 83, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    // { "name": "Paroaria gularis", "brand": "Topiclounge", "size": 38, "price": 69, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Myotis lucifugus", "brand": "Ailane", "size": 42, "price": 48, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Blue" },
    // { "name": "Zosterops pallidus", "brand": "Realbridge", "size": 42, "price": 69, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Maroon" },
    // { "name": "Canis aureus", "brand": "Mydo", "size": 35, "price": 24, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Crimson" },
    // { "name": "Macaca radiata", "brand": "Voomm", "size": 35, "price": 42, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Yellow" },
    // { "name": "Geochelone radiata", "brand": "Photobug", "size": 38, "price": 93, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Teal" },
    // { "name": "Panthera leo", "brand": "Vinte", "size": 40, "price": 80, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Semnopithecus entellus", "brand": "Eare", "size": 39, "price": 30, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Orange" },
    // { "name": "Trichoglossus chlorolepidotus", "brand": "Photospace", "size": 40, "price": 58, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Violet" },
    // { "name": "Pavo cristatus", "brand": "Zoombeat", "size": 38, "price": 31, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Goldenrod" },
    // { "name": "Larus novaehollandiae", "brand": "Skinder", "size": 41, "price": 24, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Pink" },
    // { "name": "Ephipplorhynchus senegalensis", "brand": "Voonyx", "size": 41, "price": 36, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Crimson" },
    // { "name": "Hystrix cristata", "brand": "Yakidoo", "size": 40, "price": 22, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Maroon" },
    // { "name": "Corvus brachyrhynchos", "brand": "JumpXS", "size": 41, "price": 33, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Crimson" },
    // { "name": "Hippopotamus amphibius", "brand": "Trupe", "size": 42, "price": 79, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    // { "name": "Carduelis pinus", "brand": "Omba", "size": 38, "price": 71, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Pink" },
    // { "name": "Funambulus pennati", "brand": "Mycat", "size": 37, "price": 33, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Mauv" },
    // { "name": "Papio cynocephalus", "brand": "Jazzy", "size": 41, "price": 78, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    // { "name": "Hippotragus niger", "brand": "JumpXS", "size": 41, "price": 92, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Crimson" },
    // { "name": "Gazella thompsonii", "brand": "Linkbridge", "size": 36, "price": 47, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Turquoise" },
    // { "name": "Martes americana", "brand": "Gabspot", "size": 42, "price": 80, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Fuscia" },
    // { "name": "Connochaetus taurinus", "brand": "Tambee", "size": 35, "price": 52, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Indigo" },
    // { "name": "Otocyon megalotis", "brand": "Meevee", "size": 40, "price": 78, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Aquamarine" },
    // { "name": "Sylvicapra grimma", "brand": "Yodoo", "size": 38, "price": 15, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Goldenrod" },
    // { "name": "Anastomus oscitans", "brand": "DabZ", "size": 37, "price": 69, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Indigo" },
    // { "name": "Junonia genoveua", "brand": "Demizz", "size": 36, "price": 75, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Goldenrod" },
    // { "name": "Neotoma sp.", "brand": "Skiba", "size": 37, "price": 10, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Fuscia" },
    // { "name": "Milvago chimachima", "brand": "Flipopia", "size": 42, "price": 78, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    // { "name": "Pavo cristatus", "brand": "Topdrive", "size": 35, "price": 11, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Yellow" },
    // { "name": "Dusicyon thous", "brand": "Centizu", "size": 41, "price": 70, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Mauv" },
    // { "name": "Neophoca cinerea", "brand": "Oyoba", "size": 39, "price": 15, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Puce" },
    // { "name": "Butorides striatus", "brand": "Skinix", "size": 39, "price": 20, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    // { "name": "Boselaphus tragocamelus", "brand": "Zoonder", "size": 40, "price": 26, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Yellow" },
    // { "name": "Myrmecobius fasciatus", "brand": "Skipfire", "size": 37, "price": 73, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Tiliqua scincoides", "brand": "Brightdog", "size": 41, "price": 91, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    // { "name": "Streptopelia senegalensis", "brand": "Flashdog", "size": 37, "price": 32, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Indigo" },
    // { "name": "Chlamydosaurus kingii", "brand": "Wikizz", "size": 37, "price": 62, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Teal" },
    // { "name": "Streptopelia decipiens", "brand": "Yozio", "size": 42, "price": 37, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Teal" },
    // { "name": "Erinaceus frontalis", "brand": "Jabbersphere", "size": 38, "price": 79, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Orange" },
    // { "name": "Lybius torquatus", "brand": "Twinte", "size": 38, "price": 14, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    // { "name": "Phalacrocorax carbo", "brand": "Miboo", "size": 35, "price": 26, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Red" },
    // { "name": "Panthera leo", "brand": "Avaveo", "size": 35, "price": 74, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Fuscia" },
    // { "name": "Coluber constrictor", "brand": "Riffpedia", "size": 42, "price": 74, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Green" },
    // { "name": "Dicrostonyx groenlandicus", "brand": "Browsetype", "size": 35, "price": 86, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Pink" },
    // { "name": "Ara ararauna", "brand": "Skyba", "size": 35, "price": 21, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Crimson" },
    // { "name": "Ciconia episcopus", "brand": "Edgeblab", "size": 39, "price": 42, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    // { "name": "Macropus rufogriseus", "brand": "Brainbox", "size": 42, "price": 32, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Purple" },
    // { "name": "Cacatua tenuirostris", "brand": "Flipopia", "size": 40, "price": 35, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    // { "name": "Sciurus niger", "brand": "Trilia", "size": 40, "price": 17, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Violet" },
    // { "name": "Genetta genetta", "brand": "Twinder", "size": 38, "price": 90, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Maroon" },
    // { "name": "Vulpes chama", "brand": "Janyx", "size": 41, "price": 79, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Fuscia" },
    // { "name": "Mycteria ibis", "brand": "Geba", "size": 41, "price": 69, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Pink" },
    // { "name": "Corvus albicollis", "brand": "Katz", "size": 37, "price": 37, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Yellow" },
    // { "name": "Cygnus atratus", "brand": "Jaxworks", "size": 39, "price": 55, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    // { "name": "unavailable", "brand": "Yozio", "size": 40, "price": 13, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Violet" },
    // { "name": "Choloepus hoffmani", "brand": "Gabcube", "size": 40, "price": 59, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Crimson" },
    // { "name": "Mycteria leucocephala", "brand": "Midel", "size": 39, "price": 29, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    // { "name": "Vulpes chama", "brand": "Skyvu", "size": 41, "price": 83, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Khaki" },
    // { "name": "Cebus apella", "brand": "Vidoo", "size": 39, "price": 79, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Dasypus novemcinctus", "brand": "Quimba", "size": 39, "price": 92, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Khaki" },
    // { "name": "Parus atricapillus", "brand": "Voonder", "size": 37, "price": 19, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    // { "name": "unavailable", "brand": "Avaveo", "size": 38, "price": 37, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Blue" },
    // { "name": "Phoca vitulina", "brand": "Jaxworks", "size": 38, "price": 50, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Maroon" },
    // { "name": "Phoca vitulina", "brand": "Jayo", "size": 36, "price": 55, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Khaki" },
    // { "name": "Tragelaphus scriptus", "brand": "Pixoboo", "size": 42, "price": 20, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Mauv" },
    // { "name": "Myotis lucifugus", "brand": "Feedmix", "size": 35, "price": 95, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Indigo" },
    // { "name": "Ovis ammon", "brand": "Rhycero", "size": 40, "price": 14, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Red" },
    // { "name": "Acridotheres tristis", "brand": "Fiveclub", "size": 36, "price": 21, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Ploceus intermedius", "brand": "Bubbletube", "size": 37, "price": 57, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Eumetopias jubatus", "brand": "Agimba", "size": 37, "price": 95, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Khaki" },
    // { "name": "Phascogale calura", "brand": "Zoomzone", "size": 38, "price": 87, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Indigo" },
    // { "name": "Oxybelis fulgidus", "brand": "Pixoboo", "size": 35, "price": 47, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Violet" },
    // { "name": "Neotis denhami", "brand": "Oloo", "size": 41, "price": 68, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Purple" },
    // { "name": "Mazama gouazoubira", "brand": "Edgeblab", "size": 35, "price": 23, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Pink" },
    // { "name": "Ephippiorhynchus mycteria", "brand": "Babblestorm", "size": 35, "price": 96, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    // { "name": "Nyctanassa violacea", "brand": "Realcube", "size": 35, "price": 78, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    // { "name": "Agkistrodon piscivorus", "brand": "Devcast", "size": 41, "price": 41, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Purple" },
    // { "name": "Pycnonotus nigricans", "brand": "Oodoo", "size": 36, "price": 70, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    // { "name": "Panthera leo persica", "brand": "Mybuzz", "size": 38, "price": 67, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Crimson" },
    // { "name": "Ephippiorhynchus mycteria", "brand": "Zooveo", "size": 35, "price": 28, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Red" },
    // { "name": "Martes pennanti", "brand": "Kimia", "size": 41, "price": 15, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Corvus albicollis", "brand": "LiveZ", "size": 41, "price": 29, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Pink" },
    // { "name": "Geochelone elegans", "brand": "Browsezoom", "size": 40, "price": 72, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    // { "name": "Pseudalopex gymnocercus", "brand": "Trilith", "size": 39, "price": 92, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Khaki" },
    // { "name": "Aonyx capensis", "brand": "Zoonoodle", "size": 36, "price": 36, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Purple" },
    // { "name": "Gyps fulvus", "brand": "Oozz", "size": 37, "price": 60, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Puce" },
    // { "name": "unavailable", "brand": "Youspan", "size": 39, "price": 75, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Blue" },
    // { "name": "Aegypius tracheliotus", "brand": "Thoughtstorm", "size": 38, "price": 12, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Orange" },
    // { "name": "Varanus albigularis", "brand": "Demizz", "size": 37, "price": 31, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Yellow" },
    // { "name": "Genetta genetta", "brand": "Centidel", "size": 38, "price": 79, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Puce" },
    // { "name": "Procyon lotor", "brand": "Npath", "size": 37, "price": 21, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    // { "name": "Cacatua galerita", "brand": "Digitube", "size": 39, "price": 86, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Teal" },
    // { "name": "Marmota monax", "brand": "Youfeed", "size": 38, "price": 22, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Violet" },
    // { "name": "Lorythaixoides concolor", "brand": "Skipfire", "size": 42, "price": 85, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Aquamarine" },
    // { "name": "Connochaetus taurinus", "brand": "Twitterbridge", "size": 37, "price": 12, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Pink" },
    // { "name": "Hymenolaimus malacorhynchus", "brand": "Minyx", "size": 38, "price": 41, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Yellow" },
    // { "name": "Phalacrocorax niger", "brand": "Voonix", "size": 38, "price": 10, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Goldenrod" },
    // { "name": "Corvus brachyrhynchos", "brand": "Brainlounge", "size": 38, "price": 75, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Turquoise" },
    // { "name": "Geococcyx californianus", "brand": "Edgeclub", "size": 36, "price": 95, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Maroon" },
    // { "name": "Paroaria gularis", "brand": "Flashspan", "size": 36, "price": 80, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Khaki" },
    // { "name": "Leptoptilos crumeniferus", "brand": "Trunyx", "size": 38, "price": 12, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Aquamarine" },
    // { "name": "Phalacrocorax brasilianus", "brand": "DabZ", "size": 38, "price": 43, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Yellow" },
    // { "name": "Estrilda erythronotos", "brand": "Jabbertype", "size": 38, "price": 46, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Blue" },
    // { "name": "Sarkidornis melanotos", "brand": "Avaveo", "size": 39, "price": 80, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Red" },
    // { "name": "Dicrostonyx groenlandicus", "brand": "Oyope", "size": 40, "price": 37, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Puce" },
    // { "name": "Dasyurus viverrinus", "brand": "Jabbertype", "size": 37, "price": 23, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Fuscia" },
    // { "name": "Cebus apella", "brand": "Photolist", "size": 35, "price": 25, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Aquamarine" },
    // { "name": "Columba livia", "brand": "Zooveo", "size": 35, "price": 69, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Khaki" },
    // { "name": "Eutamias minimus", "brand": "Devbug", "size": 35, "price": 85, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Crimson" },
    // { "name": "Ploceus rubiginosus", "brand": "Bubbletube", "size": 37, "price": 60, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Green" },
    // { "name": "Certotrichas paena", "brand": "Jabbercube", "size": 41, "price": 34, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Khaki" },
    // { "name": "unavailable", "brand": "Jabbersphere", "size": 41, "price": 20, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Maroon" },
    // { "name": "Colobus guerza", "brand": "Feedmix", "size": 39, "price": 15, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Turquoise" },
    // { "name": "Galago crassicaudataus", "brand": "Youspan", "size": 42, "price": 97, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Blue" },
    // { "name": "Laniarius ferrugineus", "brand": "Brainbox", "size": 36, "price": 66, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Goldenrod" },
    // { "name": "Pteropus rufus", "brand": "Lazzy", "size": 40, "price": 24, "image": "http://dummyimage.com/250x250.png/cc0000/ffffff", "color": "Yellow" },
    // { "name": "Ara macao", "brand": "Vipe", "size": 37, "price": 82, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Red" },
    // { "name": "Isoodon obesulus", "brand": "Gabtune", "size": 41, "price": 66, "image": "http://dummyimage.com/250x250.png/ff4444/ffffff", "color": "Green" },
    // { "name": "Petaurus breviceps", "brand": "Twinder", "size": 38, "price": 76, "image": "http://dummyimage.com/250x250.png/dddddd/000000", "color": "Violet" },
    // { "name": "Tringa glareola", "brand": "Twimm", "size": 35, "price": 96, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Blue" },
    // { "name": "Hippotragus equinus", "brand": "Skyba", "size": 37, "price": 20, "image": "http://dummyimage.com/250x250.png/5fa2dd/ffffff", "color": "Green" }
]